// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTrack.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyTrack.Persistence.Migrations
{
    [DbContext(typeof(MoneyTrackDbContext))]
    [Migration("20250807072309_convert_enum_role")]
    partial class convert_enum_role
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyTrack.Domain.Entities.ApiUsageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("CallCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ApiName", "CallDate")
                        .IsUnique();

                    b.ToTable("api_usage", (string)null);
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("af2b2a21-21e7-41a2-8727-c67816796132"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 7, 7, 23, 9, 638, DateTimeKind.Utc).AddTicks(7290),
                            Description = "Administrator role",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("4c5d1784-f350-49da-861c-92c486b4b46c"),
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 8, 7, 7, 23, 9, 638, DateTimeKind.Utc).AddTicks(7540),
                            Description = "Guest role",
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.TransactionCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("transaction_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3e7df94-22d7-4f8e-9f1d-9f8eb6dfc1c2"),
                            Code = "SHOPPING_001",
                            Description = "Mua Sắm, Điện tử & Công nghệ, Điện tử & Công nghệ, Điện tử & Công nghệ.",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("0c1a8bde-4e0a-43b2-a8e6-68ad3e2f8fb2"),
                            Code = "ENTERTAINMENT_001",
                            Description = "Giải Trí, xem phim, mua gói netflix, HBO, spotify, apple music, sách, truyện tranhTham gia các trò chơi tốn phí, cầu lông, tennis, bóng bàn, bóng rổTham gia các hoạt động giải trí như di concert, ca nhạc, karaoke, hát hò, nhảy múa, barĐi nhậu",
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("e4d93c9e-1c0f-44c6-bb67-7fc74d3c1e6f"),
                            Code = "TRAVEL_001",
                            Description = "Du Lịch, vé máy bay, vé tàu, vé xe, khách sạn, homestay, resort, tour du lịch, vé tham quan, vé vào cổngvé vào cổng khu du lịchPhí dic vụ, phí hướng dẫn viên, phí hướng dẫn viên, phí hướng dẫn viên",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("88d9d4e4-8a6d-42b9-9495-74bfe29c1b97"),
                            Code = "FOOD_001",
                            Description = "Ăn Uống, nhà hàng, quán ăn, quán cà phê, quán trà sữa, quán kem, quán bánh mì, quán phở, quán cơm, buffetsiêu thị, cửa hàng tiện lợi, cửa hàng thực phẩm, cửa hàng thực phẩm, cửa hàng thực phẩm, bách hóa xanh, winmartmì gói, trà, bánh kẹo, snack, dinh dưỡng",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("fa7eb29d-bbdf-4e49-a5df-f173d9c7c27e"),
                            Code = "FIXED_001",
                            Description = "Chi Phí Cố Định, tiền nhà, tiền điện, tiền nước, tiền internet, tiền mạng, phí vệ sinh, tiền gửi xe hàng thángBảo hiểm, bảo hiểm nhân thọ, trả góp tín dụng, học phí, thẻ hội viên gym, bơi, cầu lông, yoga, thể hìnhthực phẩm chức năng, thực phẩm chức năng, thực phẩm chức năngĐăng ký Netflix, Spotify, YouTube Premium",
                            Name = "Fixed Cost"
                        },
                        new
                        {
                            Id = new Guid("b72c7b35-cf25-4df7-930b-9ebfa237cd6a"),
                            Code = "EDUCATION_001",
                            Description = "Giáo Dục, học phí, chứng chỉ, gia sư, luyện thi, trung tâm, học nghề, sách, dụng cụ học tập, phần mềm học tập",
                            Name = "Education"
                        },
                        new
                        {
                            Id = new Guid("fb91ef86-df65-4d66-bb2b-62e6d8c5d29d"),
                            Code = "HEALTH_CARE_001",
                            Description = "Sức Khỏe, thực phẩm chức năng, thực phẩm chức năng, thực phẩm chức năng, viện phí, khám chữa bệnh, phẫu thuật, xét nghiệm, Mua thuốc theo đơn, thuốc không kê đơnMua thuốc theo đơn, thuốc không kê đơn, Mua thuốc theo đơn, thuốc không kê đơn, Mua thuốc theo đơn, thuốc không kê đơntư vấn trị liệu tâm lý, mát xa, mát sa, bia ôm",
                            Name = "Health Care"
                        },
                        new
                        {
                            Id = new Guid("c9da16f1-87ad-4ddb-924f-4ea7bea5a175"),
                            Code = "INVESTMENT_001",
                            Description = "Đầu tư, Đầu tư chứng khoán, đầu tư bất động sản, tiền ảo, bitcoin, chứng chỉ quỹ, quỹ đầu tư, trái phiếu, nuối trồng thủy sản, hải sản, xây dựng, mở quán cafe, start-up.",
                            Name = "Investment"
                        },
                        new
                        {
                            Id = new Guid("25949f3f-6170-4544-9683-a5a920c0d204"),
                            Code = "LIVING_001",
                            Description = "Grab, bee, now, giao hàng, Uber, xe ôm, cắt tóc, cạo râu, gội đầu, 4g, thú cưng.",
                            Name = "Living"
                        },
                        new
                        {
                            Id = new Guid("82a956cc-037f-4866-8008-d641448c485e"),
                            Code = "UNFORESEEN_001",
                            Description = "Bất Ngờ, sửa chữa, thay thế, mua mới, mất mát, hỏng hóc, hỏng hóc, hỏng hóc, hỏng hóc, hỏng hócĐám cưới, đám tang, sinh nhật, lễ tết, lễ hội, lễ hội, lễ hội, lễ hội, lễ hộiQuà tặng, Quà sinh nhật, quà 8/3, quà 14/2",
                            Name = "Unforeseen"
                        });
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.TransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.TransactionEntity", b =>
                {
                    b.HasOne("MoneyTrack.Domain.Entities.TransactionCategoryEntity", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyTrack.Domain.Entities.UserEntity", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("MoneyTrack.Domain.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyTrack.Domain.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.TransactionCategoryEntity", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyTrack.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
